spring.application.name=aem-blog-backend
# Public - no authentication required
app.security.access.public[0]=POST:/api/login
app.security.access.public[1]=GET:/swagger-ui.html
app.security.access.public[2]=GET:/swagger-ui/**
app.security.access.public[3]=GET:/v3/api-docs
app.security.access.public[4]=GET:/v3/api-docs/**
app.security.access.public[5]=GET:/swagger-resources/**
app.security.access.public[6]=GET:/webjars/**
##
app.security.access.public[7]=GET:/api/post
app.security.access.public[8]=GET:/api/post/**
app.security.access.public[9]=GET:/api/category
app.security.access.public[10]=GET:/api/category/**
app.security.access.public[11]=GET:/api/post/image
app.security.access.public[12]=GET:/api/comment
app.security.access.public[13]=POST:/api/comment
app.security.access.public[14]=POST:/api/subscriber
app.security.access.public[15]=POST:/api/contact/send
app.security.access.public[16]=PUT:/api/subscriber/unsubscribe/**
# Read - requires CAN_READ or CAN_WRITE
# Read - requires CAN_READ or CAN_WRITE
app.security.access.read[0]=GET:/api/subscriber
# Write - requires CAN_WRITE only
# Write - requires CAN_WRITE only
app.security.access.write[0]=POST:/api/category
app.security.access.write[1]=PUT:/api/category/**
app.security.access.write[2]=DELETE:/api/category/**
app.security.access.write[3]=POST:/api/post
app.security.access.write[4]=PUT:/api/post/**
app.security.access.write[5]=DELETE:/api/post/**
app.security.access.write[6]=POST:/api/post/image
app.security.access.write[7]=PATCH:/api/subscriber/**
app.security.access.write[8]=PUT:/api/comment/**
app.security.access.write[9]=DELETE:/api/comment/**


